# Generated by Django 2.1.5 on 2019-01-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(default=None, help_text='삭제 일시', null=True)),
                ('status', models.PositiveIntegerField(help_text='상태', null=True)),
                ('title', models.CharField(help_text='제목', max_length=128)),
                ('base_price', models.IntegerField(default=0, help_text='기본 가격')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_data', models.CharField(help_text='참고 데이터', max_length=16, null=True)),
                ('status_from', models.PositiveIntegerField(help_text='상태 변경 전', null=True)),
                ('status_to', models.PositiveIntegerField(help_text='상태 변경 후', null=True)),
                ('message', models.CharField(help_text='로그 메세지', max_length=256)),
            ],
        ),
    ]
